# Generated by Django 3.2.7 on 2021-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0003_auto_20210919_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
