# Generated by Django 3.2.7 on 2021-09-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpage', '0004_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (0, 'close')], default=1),
        ),
    ]
